let primaryColor50 = '#F2F1FF';
let primaryColor100 = '#D9D5FF';
let primaryColor200 = '#CCC7FF';
let primaryColor500 = '#7F72FF';
let primaryColor600 = '#675BDB';
let primaryColor700 = '#4F44B6';
let neutrals50 = '#F8F9FA';
let neutrals100 = '#E3E5EB';
let neutrals300 = '#B9BECD';
let neutrals400 = '#A4ABBD';
let neutrals500 = '#737D9A';
let neutrals600 = '#5E6782';
let neutrals700 = '#383E4E';
let success50 = '#F4FBF7';
let success500 = '#359766';
let warning50 = '#FFFBF6';
let warning500 = '#FFAD4F';
let error50 = '#FDF4F5';
let error500 = '#D1293D';
let stroke = '#E4E6E9';
let white = '#FFF';

const theme = {
    token: {
        colorPrimary: primaryColor500,
        colorPrimaryHover: primaryColor600,
        colorPrimaryActive: primaryColor700,
        colorBgContainerDisabled: neutrals100,
        colorTextDisabled: neutrals400,
        colorSuccess: success500,
        colorWarning: warning500,
        colorError: error500,
        fontFamily: 'Inter, sans-serif',
        borderRadius: 4,
    },
    components: {
        Button: {
            defaultColor: primaryColor500,
            defaultBorderColor: primaryColor500,
            defaultHoverColor: primaryColor600,
            defaultHoverBorderColor: primaryColor600,
            defaultActiveColor: primaryColor700,
            defaultActiveBorderColor: primaryColor700,
            colorTextDisabled: neutrals400,
            colorBgContainerDisabled: neutrals100,
            fontSize: 12,
            controlHeightSM: 24,
            controlHeight: 28,
            controlHeightLG: 32,
            contentFontSizeLG: 13,
            // paddingBlockSM: 4,
            paddingInlineSM: 10,
            // paddingBlock: 6,
            paddingInline: 10,
            // paddingBlockLG: 11,
            paddingInlineLG: 10,
            fontWeight: 500,
            dangerColor: error500,
            colorErrorBg: error50
        },
        Input: {
            colorBorder: stroke,
            activeBorderColor: primaryColor500,
            hoverBorderColor: primaryColor500,
            colorErrorBorderHover: error500,
            colorTextPlaceholder: neutrals300,
            colorText: neutrals700,
            colorTextDisabled: neutrals400,
            colorBgContainerDisabled: neutrals100,
            controlHeightSM: 24,
            controlHeight: 28,
            controlHeightLG: 32,
            lineHeightLG: '',
            paddingBlockSM: 1.86,
            paddingInlineSM: 7,
            paddingBlock: 3.58,
            paddingInline: 7,
            paddingBlockLG: 5.25,
            lineHeightLG: 1.5,
            paddingInlineLG: 11,
            inputFontSize: 12,
            inputFontSizeLG: 13,
            inputFontSizeSM: 12,
        },
        InputNumber: {
            colorBorder: stroke,
            activeBorderColor: primaryColor500,
            hoverBorderColor: primaryColor500,
            colorErrorBorderHover: error500,
            colorTextPlaceholder: neutrals300,
            colorText: neutrals700,
            colorTextDisabled: neutrals400,
            colorBgContainerDisabled: neutrals100,
            controlHeightSM: 24,
            controlHeight: 28,
            controlHeightLG: 32,
            lineHeightLG: '',
            paddingBlockSM: 1.86,
            paddingInlineSM: 7,
            paddingBlock: 3.58,
            paddingInline: 7,
            paddingBlockLG: 5.25,
            lineHeightLG: 1.5,
            paddingInlineLG: 11,
            inputFontSize: 12,
            inputFontSizeLG: 13,
            inputFontSizeSM: 12,
            fontSize: 12,
            fontSizeLG: 13
        },
        Select: {
            colorBorder: stroke,
            controlHeight: 28,
            controlHeightLG: 32,
            controlHeightSM: 24,
            multipleItemHeight: 22,
            multipleItemHeightLG: 26,
            multipleItemHeightSM: 18,
            fontSize: 12,
            fontSizeLG: 13,
            fontSizeSM: 12,
            optionFontSize: 13,
            optionHeight: 28,
            optionSelectedFontWeight: 600,
            borderRadius: 4,
            borderRadiusLG: 4,
            borderRadiusSM: 4,
            optionActiveBg: primaryColor50,
            optionSelectedBg: primaryColor100,
            optionSelectedColor: primaryColor500,
            colorBgContainerDisabled: neutrals100,
            colorTextDisabled: neutrals400,
            colorTextPlaceholder: neutrals300,
            colorText: neutrals700,
            paddingXXS: '4px 0px',
            multipleItemBg: primaryColor50,
            multipleItemColorDisabled: neutrals400,
            multipleSelectorBgDisabled: neutrals100,
        },
        // Table: {
        //     rowHoverBg: neutrals50,
        //     headerBg: neutrals50,
        //     cellPaddingBlock: 5.8,
        //     cellPaddingInline: 8,
        //     headerColor: neutrals600,
        //     fontSize: 11,
        //     footerBg: white
        // },
        Pagination: {
            colorText: neutrals700,
            fontSize: 12,
            itemBg: white,
            colorBorder: stroke,
            lineWidth: 1,
            lineType: 'solid',
            lineHeight: 1.66667,
            itemSize: 28,
            controlHeight: 28,
            controlHeightLG: 32,
            colorTextDisabled: neutrals400,
            colorBgContainerDisabled: neutrals100,
        },
        // Layout: {
        //     headerBg: primaryColor50,
        //     bodyBg: white,
        //     siderBg: neutrals50,
        // },
        Tabs: {
            paddingSM: 8,
            paddingXS: 4,
            paddingLG: 8,
            fontSize: 12,
            fontSizeLG: 13,
            fontSizeSM: 12,
        },
        // Card: {
        //     fontSize: 12,
        //     headerFontSize: 13,
        //     headerFontSizeSM: 12,
        //     paddingLG: 12,
        //     padding: 10,
        // },
        Tooltip: {
            colorText: white,
            fontSize: 12,
            colorBgSpotlight: "rgba(0, 0, 0, 0.75)",
        },
        DatePicker: {
            colorBorder: stroke,
            cellHoverBg: primaryColor50,
            activeBorderColor: primaryColor500,
            hoverBorderColor: primaryColor500,
            colorErrorBorderHover: error500,
            colorTextPlaceholder: neutrals300,
            colorText: neutrals700,
            colorTextDisabled: neutrals400,
            colorBgContainerDisabled: neutrals100,
            cellHeight: 24,
            cellWidth: 36,
            padding: 10,
            controlHeightSM: 27.55,
            controlHeight: 31.55,
            controlHeightLG: 34.4,
            lineHeightLG: "",
            inputFontSize: 12,
            inputFontSizeLG: 13,
            inputFontSizeSM: 12,
            multipleItemHeightSM: 27.55,
            multipleItemHeight: 31.55,
            multipleItemHeightLG: 34.4,
            fontSize: 12,
            fontSizeLG: 13,
        },
        Dropdown: {
            colorText: neutrals700,
            colorBorder: stroke,
            controlHeight: 28,
            controlItemBgHover: primaryColor50,
            colorTextDisabled: neutrals400,
            controlItemBgActive: primaryColor100,
            controlItemBgActiveHover: primaryColor100,
            fontSize: 12,
            paddingBlock: 5,
            controlPaddingHorizontal: 8,
            paddingXXS: '4px 0px',
            sizePopupArrow: 14,
        },
        Checkbox: {
            colorText: neutrals700,
            colorBorder: stroke,
            controlInteractiveSize: 18,
            colorPrimary: primaryColor500,
            colorPrimaryHover: primaryColor600,
            colorPrimaryBorder: primaryColor500,
            colorTextDisabled: neutrals400,
            colorBgContainerDisabled: neutrals100,
            fontSize: 12,
            fontSizeLG: 13,
        },
        Radio: {
            colorText: neutrals700,
            colorBorder: stroke,
            colorTextDisabled: neutrals400,
            colorBgContainerDisabled: neutrals100,
            colorPrimaryHover: primaryColor600,
            colorPrimaryBorder: primaryColor500,
            radioSize: 18,
            dotSize: 9,
            buttonSolidCheckedBg: primaryColor500,
            buttonSolidCheckedActiveBg: primaryColor500
        },
        Switch: {
            fontSize: 13,
            handleBg: white,
            colorText: neutrals700,
            colorBorder: stroke,
            colorPrimary: primaryColor500,
            colorPrimaryHover: primaryColor600,
            colorTextDisabled: neutrals400,
            colorBgContainerDisabled: neutrals100,
        },
        // Slider: {
        //     trackBg: primaryColor500,
        //     handleColor: primaryColor500,
        //     trackHoverBg: primaryColor600,
        //     colorPrimaryBorderHover: primaryColor600,
        //     dotActiveBorderColor: primaryColor500,
        //     handleActiveColor: primaryColor500,
        //     railBg: primaryColor100,
        //     railHoverBg: primaryColor100,
        //     handleSize: 14,
        //     handleSizeHover: 14,
        //     railSize: 8,
        //     borderRadiusXS: 40,
        //     trackBgDisabled: primaryColor200
        // },
        Menu: {
            fontSize: 12,
            fontSizeLG: 13,
            itemSelectedBg: primaryColor100,
            itemSelectedColor: primaryColor500,
            itemHoverBg: primaryColor50,
            itemDisabledColor: neutrals300,
            itemColor: neutrals500,
            itemActiveBg: primaryColor500,
            colorTextDisabled: neutrals400,
            colorBgContainerDisabled: neutrals100,
            itemHeight: 32,
            controlHeight: 28,
            controlHeightLG: 32,
            fontSizeSM: 12,
            padding: '4px 0px',
            paddingXL: '4px 0px',
            paddingXS: '4px 0px',
        },
        // Form: {
        //     controlHeight: 28,
        //     controlHeightLG: 32,
        //     fontSize: 12,
        //     fontSizeLG: 12,
        //     verticalLabelPadding: "0 0 4px"
        // },
        Popover: {
            // fontSize: 12,
            // colorText: neutrals400,
            sizePopupArrow: 16,
        },
        Typography: {
            fontSize: 12,
        },
        Tag: {
            fontSize: 11,
            borderRadiusSM: 4,
            colorSuccessBorder: white,
            colorSuccess: success500,
            colorSuccessBg: success50,
            colorWarningBorder: white,
            colorWarning: warning500,
            colorWarningBg: warning50,
            colorTextDisabled: neutrals400,
            colorBgContainerDisabled: neutrals100,
            colorError: error500,
            colorErrorBorder: white,
            colorErrorBg: error50,
        },
        Modal: {
            headerBg: neutrals50,
            fontSize: 12,
            fontSizeHeading5: 14,
            fontSizeLG: 13,
            titleFontSize: 14,
            padding: 10,
        },
        // Collapse: {
        //     fontSize: 12,
        //     fontSizeLG: 14
        // },
        Notification: {
            // fontSize: 12,
            // fontSizeLG: 14,
        }
    },
    hashed: false,
};
export { theme };